sudo: required
services:
  - docker

before_install:
  - docker build -t yarabdul/docker-react -f Dockerfile.dev .

script:
  - docker run yarabdul/docker-react


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-970656013945"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key: $AWS_SECRET_KEY
